import type { Map } from 'maplibre-gl';
import type { Writable } from 'svelte/store';
import { writable } from 'svelte/store';

export const activeIndex = writable(-1);
export const areaActive = writable(false);
export const areaGeoJSON = writable({});
export const areaProperties: Writable<string[]> = writable([]);
export const choices: Writable<unknown[]> = writable([]);
export const data = writable([]);
export const formValid = writable(false);
export const map: Writable<Map> = writable();
export const survey: Writable<unknown[]> = writable([]);
export const vizChoice = writable([]);
export const vizChartType = writable('STACKED');
export const vizChoiceLabel = writable([]);
export const vizDataType = writable(null);
export const vizDateGroup = writable('yearweek');
export const vizDateField = writable(null);
export const vizDateFrom = writable(null);
export const vizDateTo = writable(null);
export const vizDisplayType = writable('MAP');
export const vizField = writable('');
export const vizFieldLabel = writable('');
export const vizHover = writable({});
export const vizMax = writable(0);
export const vizMethod = writable(null);
export const vizNumerical = writable([]);
export const vizNumericalLabel = writable([]);
export const vizType = writable('');
export const vizVisable = writable(false);
export const vizFilters = writable([]);
export const vizFilterArea = writable(['', []]);
